spring:
  profiles:
    active: local
 
mail:
   host: smtp.gmail.com
   port: 587
   username: abhishekpandey81299@gmail.com
   password: 'uokelcttezoubmde'
   properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true  


image:
  upload:
    path: C:/Deskbook/images/
          
          
